### ISSUE TITLE
Would you consider publishing to ModRinth?

### ISSUE THREAD

**Issue by ryantheleach** [OKTW-Network/Galaxy-resourcepack#10]
I know it's MIT Licensed, so as long as I provide attribution I could do it myself, but figured I'd ask permission first to save the maintenance headache.

Would you be willing to publish the non-server specific GUI stuff as a separate resource pack, and publish it on Modrinth or something?

It would be nice to have something to counter the various paid and proprietary projects, given that resource packs can be easily cleanly merged with the new introduction of the `minecraft:item_model` [Data Component](https://www.minecraft.net/en-us/article/minecraft-snapshot-24w36a#:~:text=minecraft%3Aitem_model) in 24w36a.

**Comment by bill96012** [comment]
hmm, I wasn't expecting this to interest someone.
I am willing to make one later on, still, feel free to make it yourself.

**Comment by bill96012** [comment]
The resource pack has been made to a [repository](https://github.com/OKTW-Network/GUItem) and published on the [Modrinth](https://modrinth.com/resourcepack/guitem). 🥳
